name: Deploy Beta to VPS

on:
  push:
    branches:
      - beta

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying application to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }} # Default is 22 if not specified
          script: |
            echo "Starting deployment to VPS..."
            
            # Navigate to the project directory (Change this path according to your VPS setup)
            cd /var/www/mailer
            
            # Fetch latest changes
            git fetch origin beta
            
            # Reset any local changes to ensure a clean pull
            git reset --hard origin/beta
            
            # Install latest dependencies
            npm install
            
            # Update database schema
            npx prisma generate
            npx prisma db push --accept-data-loss
            
            # Build the Next.js application
            npm run build
            
            # Restart the PM2 process (Assuming you named the PM2 process 'mailer-beta')
            pm2 restart mailer-beta || pm2 start npm --name "mailer-beta" -- run start
            
            echo "Deployment successful!"
