name: Deploy Beta to VPS

on:
  push:
    branches:
      - beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 92.113.149.184
          username: mrbro
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/mailer
            git fetch --all
            git reset --hard origin/beta
            npm install
            npx prisma generate
            npx prisma db push --accept-data-loss
            npm run build
            pm2 restart mailer --update-env
            pm2 save
