name: Deploy Beta to VPS

on:
  push:
    branches:
      - beta

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying application to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "Starting deployment to VPS..."
            
            cd /var/www/mailer
            
            git pull origin beta
            
            npm install
            
            npx prisma generate
            npx prisma db push --accept-data-loss
            
            npm run build
            
            pm2 startOrRestart ecosystem.config.js
            
            echo "Deployment successful!"
